# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_sample <- function(A, n) {
    .Call(`_VCGSS_my_sample`, A, n)
}

rInvGauss <- function(mu, l) {
    .Call(`_VCGSS_rInvGauss`, mu, l)
}

mmax <- function(a, b) {
    .Call(`_VCGSS_mmax`, a, b)
}

mmin <- function(a, b) {
    .Call(`_VCGSS_mmin`, a, b)
}

rmnorm <- function(mean, Sigma) {
    .Call(`_VCGSS_rmnorm`, mean, Sigma)
}

rmnorm_svd <- function(r, mean, V, s) {
    .Call(`_VCGSS_rmnorm_svd`, r, mean, V, s)
}

rmnorm_svd2 <- function(mean, V, s) {
    .Call(`_VCGSS_rmnorm_svd2`, mean, V, s)
}

gl_vcm_cpp <- function(Y, X, settings, init) {
    .Call(`_VCGSS_gl_vcm_cpp`, Y, X, settings, init)
}

sample_int <- function(n, min, max) {
    .Call(`_VCGSS_sample_int`, n, min, max)
}

sumlogs <- function(a, b) {
    .Call(`_VCGSS_sumlogs`, a, b)
}

ss_vcm_cpp <- function(Y, X, settings, init, var_gp) {
    .Call(`_VCGSS_ss_vcm_cpp`, Y, X, settings, init, var_gp)
}

ss_vcm_without_rho_cpp <- function(Y, X, settings, init, var_gp) {
    .Call(`_VCGSS_ss_vcm_without_rho_cpp`, Y, X, settings, init, var_gp)
}

vcm_cpp <- function(Y, X, settings, init, var_gp) {
    .Call(`_VCGSS_vcm_cpp`, Y, X, settings, init, var_gp)
}

