# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mySample <- function(A, n) {
    .Call(`_VCGSS_mySample`, A, n)
}

rInvGauss <- function(mu, l) {
    .Call(`_VCGSS_rInvGauss`, mu, l)
}

mmax <- function(a, b) {
    .Call(`_VCGSS_mmax`, a, b)
}

mmin <- function(a, b) {
    .Call(`_VCGSS_mmin`, a, b)
}

rmnorm <- function(mean, Sigma) {
    .Call(`_VCGSS_rmnorm`, mean, Sigma)
}

rmnormSvd <- function(r, mean, V, s) {
    .Call(`_VCGSS_rmnormSvd`, r, mean, V, s)
}

rmnormSvd2 <- function(mean, V, s) {
    .Call(`_VCGSS_rmnormSvd2`, mean, V, s)
}

sampleInt <- function(n, min, max) {
    .Call(`_VCGSS_sampleInt`, n, min, max)
}

sumlogs <- function(a, b) {
    .Call(`_VCGSS_sumlogs`, a, b)
}

ssVcmCpp <- function(Y, X, settings, init, var_gp) {
    .Call(`_VCGSS_ssVcmCpp`, Y, X, settings, init, var_gp)
}

vcmCpp <- function(Y, X, settings, init, var_gp) {
    .Call(`_VCGSS_vcmCpp`, Y, X, settings, init, var_gp)
}

